name: CI

on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:

jobs:
  smoke:
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      CI: true
      RAILS_VERSION: ${{ matrix.rails_version }}
    services:
      redis:
        image: redis:7.0-alpine
        ports: ["6379:6379"]
        options: --health-cmd="redis-cli ping" --health-interval 1s --health-timeout 3s --health-retries 30
    strategy:
      fail-fast: false
      matrix:
        server: ["puma", "anycable"]
        scenario: ["echo", "broadcast"]
        rails_version: ["dev", "7"]
        include:
          - server: "iodine"
            rails_version: "dev"
            scenario: "broadcast"
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3
        bundler-cache: true
    - name: Run server
      run: |
        bundle exec bento --${{ matrix.server }} &
        bin/wait_tcp 8080
    - name: Run WS director scenario
      run: |
        SCENARIO=${{ matrix.scenario }} make wsdirector

  conformance:
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      CI: true
      RAILS_VERSION: ${{ matrix.rails_version }}
    services:
      redis:
        image: redis:7.0-alpine
        ports: ["6379:6379"]
        options: --health-cmd="redis-cli ping" --health-interval 1s --health-timeout 3s --health-retries 30
    strategy:
      fail-fast: false
      matrix:
        server: ["puma", "anycable"]
        rails_version: ["dev", "7"]
        include:
          - server: "iodine"
            rails_version: "dev"
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3
        bundler-cache: true
    - name: Run conformance tests via AnyT
      run: |
        make anyt-${{ matrix.server }}
